### ISSUE TITLE
NetCDF output does not display correctly in QGIS

### ISSUE THREAD

**Issue by wcarthur** [GeoscienceAustralia/tcrm#25]
NetCDF4 files do not project correctly in QGIS (2.14.4). Appears to be a problem with the underlying GDAL libraries (see https://trac.osgeo.org/gdal/ticket/5873 and http://nbviewer.jupyter.org/gist/bnordgren/47eee80aae57deb303a0 for a fix)

**Comment by CEKrause** [comment]
Issue trying to use gdal_translate to convert netcdf gust file to geotiff. From the command line, typing
> gdal_translate -of GTiff NETCDF:'gust.001-00001.nc':vmax Yasi_min_Vmax.tif
gives this error
> Input file size is 1251, 601
0ERROR 1: nBlockYSize = 601, only 1 supported when reading bottom-up dataset

Suggested bug fix to explicitly set the way bottom-up datasets are handled
>  export GDAL_NETCDF_BOTTOMUP=NO
then rerun the gdal_translate code line
This successfully runs without any errors, but produced a geotiff that is upside down when read into ArcGIS (same as the issue identified here)

Possible work around in netCDF4 to explicitly set the netCDF chunksize (see https://trac.osgeo.org/gdal/ticket/5291)
Implemented by adding chunksizes to the ncSaveGrid function within Utilities/nctools.py, to both the function definition, and the var= statement. 
Resulted in the following error:
> 2017-03-16 11:43:03: chunksizes=chunksizes)
2017-03-16 11:43:03: File "netCDF4/_netCDF4.pyx", line 2263, in netCDF4._netCDF4.Dataset.createVariable (netCDF4/_netCDF4.c:18755)
2017-03-16 11:43:03: File "netCDF4/_netCDF4.pyx", line 3220, in netCDF4._netCDF4.Variable.__init__ (netCDF4/_netCDF4.c:31245)

This particular error was identified and fixed in an early version of netcdf4 (see https://github.com/Unidata/netcdf4-python/issues/66, comment about 2/3 down the page). Possible that this error persists due to an old version of the netcdf library somewhere on NCI, but updating didn't seem to help.

Bug fixing ongoing...

**Comment by CEKrause** [comment]
Updating to add extra line of netCDF chunksize error:
> TypeError: object of type 'int' has no len()

**Comment by CEKrause** [comment]
Another possible fix, but not sure where to implement https://lists.osgeo.org/pipermail/gdal-dev/2015-January/040744.html

**Comment by CEKrause** [comment]
Successful work around for gdal_translate:
Turn off compression in Utilities/nctools.py - ncSaveGrid, by setting zlib=False.
Gdal then successfully creates a geotiff from the netcdf file that is properly read in my arcGIS. Caveat that with compression off, the geotif is larger (~3mb in my case).

**Comment by CEKrause** [comment]
netcdf file that the geotiff is written from still does not display properly in QGIS (but hacked geotiff does). Possibly due to the coordinate system not being explicitly stated in the netcdf variable attributes. The crs is currently a variable, with some info in the attributes, but may need to be more explicitly written for QGIS to interpret?

**Comment by wcarthur** [comment]
Fixed with PR #36
