### ISSUE TITLE
Port Headland example script slice error

### ISSUE THREAD

**Issue by CEKrause** [GeoscienceAustralia/tcrm#27]
13:20:16: Traceback (most recent call last):
13:20:16: File "tcrm.py", line 634, in startup
13:20:16: main(configFile)
13:20:16: File "tcrm.py", line 53, in wrap
13:20:16: res = f(*args, **kwargs)
13:20:16: File "tcrm.py", line 516, in main
13:20:16: doStatistics(configFile)
13:20:16: File "c:\Users\u37443\TCRM\Utilities\parallel.py", line 70, in wrap
13:20:16: return f(*args, **kwargs)
13:20:16: File "tcrm.py", line 357, in doStatistics
13:20:16: statInterface.kdeGenesisDate()
13:20:16: File "c:\Users\u37443\TCRM\StatInterface\StatInterface.py", line 122,
in kdeGenesisDate
13:20:16: kdeStep=0.25, periodic=365)
13:20:16: File "c:\Users\u37443\TCRM\StatInterface\GenerateDistributions.py", li
ne 173, in allDistributions
13:20:16: periodic=periodic)
13:20:16: File "c:\Users\u37443\TCRM\StatInterface\KDEParameters.py", line 142,
in generateKDE
13:20:16: self.pdf = 3.0*self.pdf[(periodic/kdeStep):2*(periodic/kdeStep)]
13:20:16: TypeError: slice indices must be integers or None or have an __index__
 method

**Comment by wcarthur** [comment]
Using numpy v1.11.2, it runs, but raises a warning:
13:24:11: Initialising KDEParameters
c:\WorkSpace\tcrm\StatInterface\KDEParameters.py:142: VisibleDeprecationWarning:
 using a non-integer number instead of an integer will result in an error in the
 future
  self.pdf = 3.0*self.pdf[(periodic/kdeStep):2*(periodic/kdeStep)]
c:\WorkSpace\tcrm\StatInterface\KDEParameters.py:143: VisibleDeprecationWarning:
 using a non-integer number instead of an integer will result in an error in the
 future
  self.grid = self.grid[(periodic/kdeStep):2*(periodic/kdeStep)]
