### ISSUE TITLE
Start File to Run Whole Application and Building Errors

### ISSUE THREAD

**Issue by MrKyaw** [GeoscienceAustralia/tcrm#31]
Dear All,

How to start to run here pls(may be run.py ?) and there were building errors that I will put in place soon.

Kindly advise me since I am new in here.

Best regards
Kenneth

**Comment by CEKrause** [comment]
Here is the documentation for TCRM, in case you haven't found this yet. I will add a link to this from the README to make it easier to find. http://geoscienceaustralia.github.io/tcrm/

**Comment by wcarthur** [comment]
Can you provide the log messages from the build? 

Installation instructions: http://geoscienceaustralia.github.io/tcrm/docs/install.html
Running TCRM: http://geoscienceaustralia.github.io/tcrm/docs/execution.html

**Comment by MrKyaw** [comment]
Thank you Guys.

The Model can apply for the following links pls
1. http://www.tropicalstormrisk.com/
2. http://www.hko.gov.hk/cgi-bin/hko/warndb_e1.pl?opt=1&sgnl=3.
3.  http://journals.ametsoc.org/doi/full/10.1175/2008MWR2269.1
 
Really appreciate your kind advice.

**Comment by wcarthur** [comment]
Looks like you're interested in simulating an individual event. In that case, check the docs on running scenarios: http://geoscienceaustralia.github.io/tcrm/docs/scenarios.html

You'll need to use the "tcevent.py" script to do that.

**Comment by MrKyaw** [comment]
Thank you wcarthur n pls advise me the Python Version you were ok since 2.7 and 3.6 made a lot of importing libraries errors.

**Comment by wcarthur** [comment]
We use Python 2.7 currently. 

Be sure to check that all the dependencies are installed (http://geoscienceaustralia.github.io/tcrm/docs/install.html#dependencies), and that you've set the PYTHONPATH environment variable so that Python can locate the additional utilities that TCRM includes (http://geoscienceaustralia.github.io/tcrm/docs/install.html#setting-the-environment) 

I'll check that the dependency list is up to date for version 1 of the code.
