### ISSUE TITLE
extracting wind intensity CDF as a function of lat/lon

### ISSUE THREAD

**Issue by jparal** [GeoscienceAustralia/tcrm#59]
hey, great work on TCRM. i have a question regarding extracting CDF of wind intensity as a function of lat/lon. What variable holds this information? I did have a quick look at the outputs from the example run but I did not see it.
thanks, Jan

**Comment by wcarthur** [comment]
The CDF of wind intensity an any point in the domain is not something we routinely create within the simulations, in part because of the number of simulations (10,000 years) and extent that we usually run the model over (continental scale domains).

If you've run the database creation component, then the CDF can be extracted for locations within the simulation domain, but only at WMO weather stations. You'll need to use the `database.locationRecords()` function to extract all wind records at a location, then sort them into ascending order. 

The `processEvent` method in the `HazardDatabase` class (formally `_HazardDatabase`) shows how to open the wind field files and extract wind speeds at any given point - just in that case the points are specified as a location.

**Comment by jparal** [comment]
Craig, thank you. I looked at the functions and now its straightforward how to extract information I need.
I have one other question but I will open a new Issue as it is unrelated. thx
