### ISSUE TITLE
redefinition of alpha in lag-one correlation

### ISSUE THREAD

**Issue by mfshaw** [GeoscienceAustralia/tcrm#63]
Lines 248 and 249 of generateStats.py are a little confusing.  Was alpha meant to be redefined or is line 249 an error?

247         # Grab only the lag-one autocorrelation coeff.
248         alpha = alphas[n]/alphas.max()
249         alpha = acf(p)[-1]
250         phi = np.sqrt(1 - alpha**2)
251         mn = min(p)

**Comment by benjimin** [comment]
The redefinition of `alpha` seems to have occurred in commit b011e09b1, which also defined `acf()`.

The original defined `alpha = alphas[len(p)]/alphas.max()` where `alphas = np.correlate(p, p, 'full')`.

The modified definition (looking into `acf`) is `(alphas[len(p)-1:(len(p)+1)]/alphas.max())[-1]`, which should be identical to the original because `x[_:i+1][-1] == x[i]`.

I agree that it ought be coded more clearly (and efficiently), but it should make no tangible impact on the results.
