### ISSUE TITLE
Hazard maps from the Port Hedland example result

### ISSUE THREAD

**Issue by yangchino1** [GeoscienceAustralia/tcrm#73]
Dear developers,

I recently installed the docker version of this great software and ran the Port Hedland example shipped with it as is. However, the hazard maps (see the 100-year RP example below) are quite different with those shown in the software documentation or in the project homepage in github. I noticed that the model settings had changed from those given in the documentation, but the original settings seem to be incompatible with the current version. I just wonder if the new result is correct? How should I set up the example model to reproduce the figure shown in the documentation?
![100_yrRP_hazard_map](https://user-images.githubusercontent.com/43056880/59647082-7a135300-91ac-11e9-8d2d-7ea48a2a7892.png)

**Comment by acoat** [comment]
Same result with the docker version for me !
I also noticed that the file landmask.nc seems to have the latitude reversed.

**Comment by markwestcott34** [comment]
I'm getting similar output using latest code base (v2.1 branch). Running outside of Docker. Any clues?

**Comment by wcarthur** [comment]
It's a result of running a gaussian filter over the hazard data before plotting. This was done to reduce inferences about lines on maps that some non-technical users may make. When using a larger number of simulated years (more than the 1000 used in the example), this issue is eliminated.

The blue areas in the image are areas where there is no data, where there are insufficient data points to fit an extreme value distribution. These nodata areas are not handled well by the gaussian filter. 

The underlying data is not affected by this issue in the plotting routine.

**Comment by markwestcott34** [comment]
Thanks for the explanation @wcarthur ! Mark
